name: Release

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Build & Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: "darwin"
        include:
          - goarch: "arm64"
            goos: "android"
          - goarch: "arm64"
            goos: "darwin"
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.16
          executable_compression: upx
          ldflags: -s -w
          extra_files: config-sample.json
          binary_name: OmenHelper
